// src/app/shared/nav/nav.component.ts
import { Component, HostListener, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { I18nService } from '../../i18n/i18n.service';
import { LanguageSwitcherComponent } from '../language-switcher/language-switcher.component';
import { LucideAngularModule, Menu, X } from 'lucide-angular';

/* 
 * Componente di Navigazione.
 * Header fisso con effetto glassmorphism e menu responsive.
 */
@Component({
  selector: 'app-nav',
  standalone: true,
  imports: [CommonModule, RouterModule, LanguageSwitcherComponent, LucideAngularModule],
  templateUrl: './nav.component.html'
})
export class NavComponent {
  i18n = inject(I18nService);
  
  isScrolled = false;
  open = false;

  icons = { Menu, X };

  get t() {
    return this.i18n.getTranslation().nav;
  }

  get locale() {
    return this.i18n.currentLocale();
  }

  get navItems() {
    return [
      { href: `/${this.locale}#why`, label: this.t.why },
      { href: `/${this.locale}#benefits`, label: this.t.benefits },
      { href: `/${this.locale}#pricing`, label: this.t.pricing },
      { href: `/${this.locale}#impact`, label: this.t.mission },
      { href: `/${this.locale}#faq`, label: this.t.faq },
      { href: `/${this.locale}/contact`, label: this.t.contact },
    ];
  }

  @HostListener('window:scroll', [])
  onWindowScroll() {
    this.isScrolled = window.scrollY > 24;
  }

  toggleMobileMenu() {
    this.open = !this.open;
  }
}

<header class="fixed inset-x-0 top-0 z-50 transition-all duration-500" [ngClass]="isScrolled ? 'py-2' : 'py-4'">
  <div class="mx-auto flex max-w-7xl items-center justify-between rounded-full px-5 py-3 transition-all duration-500 sm:px-7"
       [ngClass]="isScrolled ? 'glass shadow-card' : ''"
       [style.marginInline]="isScrolled ? '1rem' : '1.5rem'">
    
    <a [routerLink]="['/', locale]" class="flex items-center gap-2 text-primary" aria-label="The Holy Supper">
      <svg viewBox="0 0 24 24" fill="none" class="h-5 w-5" aria-hidden="true">
        <path d="M12 2v20M6 8h12" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />
      </svg>
      <span class="text-display text-lg tracking-wide">The Holy Supper</span>
    </a>
    
    <nav class="hidden items-center gap-7 md:flex">
      <a *ngFor="let item of navItems" [href]="item.href" class="text-sm text-cream/80 transition hover:text-primary">
        {{ item.label }}
      </a>
    </nav>
    
    <div class="hidden items-center gap-3 md:flex">
      <app-language-switcher></app-language-switcher>
      <a [routerLink]="['/', locale, 'contact']"
         class="rounded-full bg-primary px-5 py-2 text-sm font-medium text-primary-foreground transition hover:brightness-110">
        {{ t.cta }}
      </a>
    </div>
    
    <div class="flex items-center gap-2 md:hidden">
      <app-language-switcher [variant]="'mobile'"></app-language-switcher>
      <button class="rounded-full border border-border p-2 text-primary" (click)="toggleMobileMenu()"
              [attr.aria-label]="t.menu" [attr.aria-expanded]="open">
        <lucide-icon *ngIf="open" [img]="icons.X" class="h-5 w-5"></lucide-icon>
        <lucide-icon *ngIf="!open" [img]="icons.Menu" class="h-5 w-5"></lucide-icon>
      </button>
    </div>
  </div>

  <div *ngIf="open" class="mx-6 mt-2 rounded-2xl glass p-6 md:hidden">
    <div class="flex flex-col gap-4">
      <a *ngFor="let item of navItems" [href]="item.href" (click)="open = false" class="text-base text-cream/90">
        {{ item.label }}
      </a>
      <a [routerLink]="['/', locale, 'contact']" (click)="open = false"
         class="mt-2 rounded-full bg-primary px-5 py-3 text-center text-sm font-medium text-primary-foreground">
        {{ t.cta }}
      </a>
    </div>
  </div>
</header>

// the-holy-supper-export/src/components/site/Nav.tsx
import { Link } from "@tanstack/react-router";
import { Menu, X } from "lucide-react";
import { useEffect, useState } from "react";
import { useT, useLocale } from "@/i18n/config";
import { LanguageSwitcher } from "./LanguageSwitcher";

export function Nav() {
  const [scrolled, setScrolled] = useState(false);
  const [open, setOpen] = useState(false);
  const t = useT();
  const loc = useLocale();

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 24);
    onScroll();
    window.addEventListener("scroll", onScroll, { passive: true });
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const nav = [
    { href: `/${loc}#why`, label: t.nav.why },
    { href: `/${loc}#benefits`, label: t.nav.benefits },
    { href: `/${loc}#pricing`, label: t.nav.pricing },
    { href: `/${loc}#impact`, label: t.nav.mission },
    { href: `/${loc}#faq`, label: t.nav.faq },
    { href: `/${loc}/contact`, label: t.nav.contact },
  ];

  return (
    <header className={`fixed inset-x-0 top-0 z-50 transition-all duration-500 ${scrolled ? "py-2" : "py-4"}`}>
      <div className={`mx-auto flex max-w-7xl items-center justify-between rounded-full px-5 py-3 transition-all duration-500 sm:px-7 ${scrolled ? "glass shadow-card" : ""}`}
        style={{ marginInline: scrolled ? "1rem" : "1.5rem" }}>
        <Link to="/$locale" params={{ locale: loc }} className="flex items-center gap-2 text-primary" aria-label="The Holy Supper">
          <Cross className="h-5 w-5" />
          <span className="text-display text-lg tracking-wide">The Holy Supper</span>
        </Link>
        <nav className="hidden items-center gap-7 md:flex">
          {nav.map((item) => (
            <a key={item.href} href={item.href} className="text-sm text-cream/80 transition hover:text-primary">{item.label}</a>
          ))}
        </nav>
        <div className="hidden items-center gap-3 md:flex">
          <LanguageSwitcher />
          <Link to="/$locale/contact" params={{ locale: loc }}
            className="rounded-full bg-primary px-5 py-2 text-sm font-medium text-primary-foreground transition hover:brightness-110">
            {t.nav.cta}
          </Link>
        </div>
        <div className="flex items-center gap-2 md:hidden">
          <LanguageSwitcher variant="mobile" />
          <button className="rounded-full border border-border p-2 text-primary" onClick={() => setOpen((v) => !v)}
            aria-label={t.nav.menu} aria-expanded={open}>
            {open ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}
          </button>
        </div>
      </div>
      {open && (
        <div className="mx-6 mt-2 rounded-2xl glass p-6 md:hidden">
          <div className="flex flex-col gap-4">
            {nav.map((item) => (
              <a key={item.href} href={item.href} onClick={() => setOpen(false)} className="text-base text-cream/90">
                {item.label}
              </a>
            ))}
            <Link to="/$locale/contact" params={{ locale: loc }} onClick={() => setOpen(false)}
              className="mt-2 rounded-full bg-primary px-5 py-3 text-center text-sm font-medium text-primary-foreground">
              {t.nav.cta}
            </Link>
          </div>
        </div>
      )}
    </header>
  );
}

export function Cross({ className = "" }: { className?: string }) {
  return (
    <svg viewBox="0 0 24 24" fill="none" className={className} aria-hidden="true">
      <path d="M12 2v20M6 8h12" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" />
    </svg>
  );
}
