// src/app/pages/contact/contact.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { SupabaseService } from '../../services/supabase.service';
import { I18nService } from '../../i18n/i18n.service';

/* 
 * Pagina di Contatto collegata a Supabase per l'invio delle richieste.
 */
@Component({
  selector: 'app-contact',
  standalone: true,
  imports: [CommonModule, RouterModule, ReactiveFormsModule],
  templateUrl: './contact.component.html',
  styleUrl: './contact.component.css'
})
export class ContactComponent {
  private fb = inject(FormBuilder);
  private supabase = inject(SupabaseService);
  i18n = inject(I18nService);

  get t() { return this.i18n.getTranslation().contact; }
  get locale() { return this.i18n.currentLocale(); }

  isSubmitting = false;
  isSuccess = false;
  errorMessage = '';

  contactForm = this.fb.group({
    churchName: ['', Validators.required],
    country: ['', Validators.required],
    firstName: ['', Validators.required],
    lastName: ['', Validators.required],
    email: ['', [Validators.required, Validators.email]],
    phone: [''],
    congregationSize: [''],
    avgAttendance: [''],
    expectedQuantity: [''],
    productInterest: [''],
    message: [''],
    notify: [false]
  });

  async onSubmit() {
    if (this.contactForm.valid) {
      this.isSubmitting = true;
      this.errorMessage = '';

      const formVal = this.contactForm.value;
      const data = {
        churchName: formVal.churchName || '',
        country: formVal.country || '',
        firstName: formVal.firstName || '',
        lastName: formVal.lastName || '',
        email: formVal.email || '',
        phone: formVal.phone || '',
        congregationSize: formVal.congregationSize || '',
        avgAttendance: formVal.avgAttendance || '',
        expectedQuantity: formVal.expectedQuantity || '',
        productInterest: formVal.productInterest || '',
        message: formVal.message || '',
        notify: !!formVal.notify,
        language: this.locale
      };

      try {
        const { error } = await this.supabase.submitPricingRequest(data);
        this.isSubmitting = false;

        if (error) {
          console.error('Supabase error:', error);
          this.errorMessage = this.t.errors.generic;
        } else {
          this.isSuccess = true;
        }
      } catch (err) {
        this.isSubmitting = false;
        this.errorMessage = this.t.errors.generic;
        console.error('Submission error:', err);
      }
    } else {
      this.contactForm.markAllAsTouched();
    }
  }
}

<main class="grain pt-32 pb-24">
  <div class="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-5">
    
    <!-- Left Column -->
    <aside class="lg:col-span-2">
      <p class="text-xs uppercase tracking-[0.3em] text-peach-soft">{{ t.eyebrow }}</p>
      <h1 class="text-display mt-4 text-4xl sm:text-5xl">{{ t.title }}</h1>
      <p class="mt-5 text-cream/75">{{ t.intro }}</p>
      
      <div class="mt-8 space-y-3 text-sm text-cream/75">
        <a href="mailto:theholysupper@gmail.com" class="flex items-center gap-2 hover:text-primary transition-colors">
          <svg class="h-4 w-4" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="2" y="4" width="20" height="16" rx="2"></rect><path d="m2 4 10 8 10-8"></path></svg>
          theholysupper&#64;gmail.com
        </a>
        <a href="tel:+393913817351" class="flex items-center gap-2 hover:text-primary transition-colors">
          <svg class="h-4 w-4" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07 19.5 19.5 0 0 1-6-6 19.79 19.79 0 0 1-3.07-8.67A2 2 0 0 1 4.11 2h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L8.09 9.91a16 16 0 0 0 6 6l1.27-1.27a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"></path></svg>
          +39 391 3817351
        </a>
      </div>

      <p class="mt-8 rounded-2xl border border-border/60 bg-card/40 p-5 text-sm text-cream/70">
        {{ t.sampleNote }}
      </p>
    </aside>

    <!-- Right Column (Form / Success) -->
    <div class="rounded-3xl border border-border/60 bg-card/40 p-8 sm:p-10 lg:col-span-3">
      
      <!-- Success View -->
      <div *ngIf="isSuccess" class="flex flex-col items-center justify-center text-center py-12">
        <span class="inline-flex h-16 w-16 items-center justify-center rounded-full bg-primary/15 text-primary mb-6">
          <svg class="h-8 w-8" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="12" cy="12" r="10"></circle>
            <path d="m9 12 2 2 4-4"></path>
          </svg>
        </span>
        <h2 class="text-display text-4xl sm:text-5xl mb-4">{{ t.successTitle }}</h2>
        <p class="text-cream/75 mb-10 max-w-md">{{ t.successBody }}</p>
        <a [routerLink]="['/', locale]" class="inline-flex items-center gap-2 rounded-full border border-border px-7 py-3.5 text-sm text-cream transition hover:border-primary hover:text-primary">
          {{ t.backHome }}
          <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path></svg>
        </a>
      </div>

      <!-- Form View -->
      <form *ngIf="!isSuccess" [formGroup]="contactForm" (ngSubmit)="onSubmit()">
        
        <div *ngIf="errorMessage" class="mb-6 rounded-xl border border-red-500/30 bg-red-500/10 p-4 text-sm text-red-200">
          {{ errorMessage }}
        </div>

        <div class="grid gap-5 sm:grid-cols-2">
          
          <!-- Church Name -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.church }}</span>
            <input 
              type="text" 
              formControlName="churchName"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Country -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.country }}</span>
            <input 
              type="text" 
              formControlName="country"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- First Name -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.firstName }}</span>
            <input 
              type="text" 
              formControlName="firstName"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Last Name -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.lastName }}</span>
            <input 
              type="text" 
              formControlName="lastName"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Email -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.email }}</span>
            <input 
              type="email" 
              formControlName="email"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Phone -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.phone }}</span>
            <input 
              type="tel" 
              formControlName="phone"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Congregation Size -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.congregation }}</span>
            <input 
              type="text" 
              formControlName="congregationSize"
              [placeholder]="t.placeholders.congregation"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Communion Attendance -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.attendance }}</span>
            <input 
              type="text" 
              formControlName="avgAttendance"
              [placeholder]="t.placeholders.attendance"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Expected Quantity -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.quantity }}</span>
            <input 
              type="text" 
              formControlName="expectedQuantity"
              [placeholder]="t.placeholders.quantity"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <!-- Preferred Product -->
          <label class="block">
            <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.product }}</span>
            <input 
              type="text" 
              formControlName="productInterest"
              [placeholder]="t.placeholders.product"
              class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

        </div>

        <!-- Message -->
        <label class="mt-5 block">
          <span class="text-xs uppercase tracking-widest text-cream/60">{{ t.fields.message }}</span>
          <textarea
            formControlName="message"
            rows="5"
            [placeholder]="t.messagePlaceholder"
            class="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
          ></textarea>
        </label>

        <!-- Checkbox Notify -->
        <label class="mt-6 flex items-start gap-3 text-sm text-cream/75 cursor-pointer">
          <input 
            type="checkbox" 
            formControlName="notify"
            class="mt-1 h-4 w-4 rounded accent-[color:var(--peach)]"
          />
          <span>{{ t.notify }}</span>
        </label>

        <!-- Submit Button -->
        <button
          type="submit"
          [disabled]="isSubmitting"
          class="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full bg-primary px-8 py-4 text-sm font-medium text-primary-foreground transition hover:brightness-110 disabled:opacity-60 cursor-pointer"
        >
          <span>{{ isSubmitting ? t.submitting : t.submit }}</span>
          <svg class="h-4 w-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"></path><path d="m12 5 7 7-7 7"></path></svg>
        </button>

      </form>
    </div>

  </div>
</main>

// the-holy-supper-export/src/routes/$locale/contact.tsx
import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { z } from "zod";
import { toast } from "sonner";
import { ArrowRight, CheckCircle2, Mail, Phone } from "lucide-react";
import {
  useT,
  useLocale,
  canonicalFor,
  hreflangLinks,
  isLocale,
  LOCALE_META,
} from "@/i18n/config";
import { TRANSLATIONS } from "@/i18n/translations";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/$locale/contact")({
  head: ({ params }) => {
    const loc = isLocale(params.locale) ? params.locale : "en";
    const d = TRANSLATIONS[loc];
    return {
      meta: [
        { title: d.contact.metaTitle },
        { name: "description", content: d.contact.metaDescription },
        { property: "og:title", content: d.contact.metaTitle },
        { property: "og:description", content: d.contact.metaDescription },
        { property: "og:url", content: canonicalFor(loc, "/contact") },
        { property: "og:locale", content: LOCALE_META[loc].htmlLang },
        { property: "og:type", content: "website" },
      ],
      links: [
        { rel: "canonical", href: canonicalFor(loc, "/contact") },
        ...hreflangLinks("/contact"),
      ],
      scripts: [
        {
          type: "application/ld+json",
          children: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "ContactPage",
            name: d.contact.metaTitle,
            description: d.contact.metaDescription,
            url: canonicalFor(loc, "/contact"),
            inLanguage: LOCALE_META[loc].htmlLang,
          }),
        },
      ],
    };
  },
  component: Contact,
});

const buildSchema = (t: ReturnType<typeof useT>) =>
  z.object({
    church: z.string().trim().min(2).max(200),
    country: z.string().trim().min(2).max(60),
    firstName: z.string().trim().min(2).max(60),
    lastName: z.string().trim().min(2).max(60),
    email: z.string().trim().email(t.contact.errors.generic).max(255),
    phone: z.string().trim().max(40).optional().or(z.literal("")),
    congregation: z.string().trim().max(40).optional().or(z.literal("")),
    attendance: z.string().trim().max(40).optional().or(z.literal("")),
    quantity: z.string().trim().max(40).optional().or(z.literal("")),
    product: z.string().trim().max(80).optional().or(z.literal("")),
    message: z.string().trim().max(2000).optional().or(z.literal("")),
  });

function Contact() {
  const t = useT();
  const loc = useLocale();
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);

  const onSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const form = e.currentTarget;
    const fd = new FormData(form);
    const raw = Object.fromEntries(fd.entries()) as Record<string, string>;
    const parsed = buildSchema(t).safeParse(raw);
    if (!parsed.success) {
      toast.error(parsed.error.issues[0]?.message ?? t.contact.errors.generic);
      return;
    }
    setSubmitting(true);
    const v = parsed.data;
    const ua = typeof navigator !== "undefined" ? navigator.userAgent : null;
    const ref = typeof document !== "undefined" ? document.referrer || null : null;
    const { error } = await supabase.from("pricing_requests").insert({
      church_name: v.church,
      country: v.country,
      first_name: v.firstName,
      last_name: v.lastName,
      email: v.email,
      phone: v.phone || null,
      congregation_size: v.congregation || null,
      communion_attendance: v.attendance || null,
      expected_quantity: v.quantity || null,
      preferred_product: v.product || null,
      message: v.message || null,
      notify_when_ordering_opens: fd.get("notify") === "on",
      language: loc,
      status: "New",
      user_agent: ua,
      referer: ref,
    });
    setSubmitting(false);
    if (error) {
      console.error(error);
      toast.error(t.contact.errors.generic);
      return;
    }
    setSubmitted(true);
    form.reset();
  };

  if (submitted) {
    return (
      <main className="grain min-h-screen pt-40 pb-32">
        <div className="mx-auto max-w-2xl px-6 text-center">
          <span className="inline-flex h-16 w-16 items-center justify-center rounded-full bg-primary/15 text-primary">
            <CheckCircle2 className="h-8 w-8" />
          </span>
          <h1 className="text-display mt-8 text-4xl sm:text-5xl">{t.contact.successTitle}</h1>
          <p className="mt-5 text-cream/75">{t.contact.successBody}</p>
          <Link
            to="/$locale"
            params={{ locale: loc }}
            className="mt-10 inline-flex items-center gap-2 rounded-full border border-border px-7 py-3.5 text-sm text-cream transition hover:border-primary hover:text-primary"
          >
            {t.contact.backHome}
            <ArrowRight className="h-4 w-4" />
          </Link>
        </div>
      </main>
    );
  }

  return (
    <main className="grain pt-32 pb-24">
      <div className="mx-auto grid max-w-6xl gap-12 px-6 lg:grid-cols-5">
        <aside className="lg:col-span-2">
          <p className="text-xs uppercase tracking-[0.3em] text-peach-soft">{t.contact.eyebrow}</p>
          <h1 className="text-display mt-4 text-4xl sm:text-5xl">{t.contact.title}</h1>
          <p className="mt-5 text-cream/75">{t.contact.intro}</p>
          <div className="mt-8 space-y-3 text-sm text-cream/75">
            <a href="mailto:theholysupper@gmail.com" className="inline-flex items-center gap-2 hover:text-primary">
              <Mail className="h-4 w-4" /> theholysupper@gmail.com
            </a>
            <br />
            <a href="tel:+393913817351" className="inline-flex items-center gap-2 hover:text-primary">
              <Phone className="h-4 w-4" /> +39 391 3817351
            </a>
          </div>
          <p className="mt-8 rounded-2xl border border-border/60 bg-card/40 p-5 text-sm text-cream/70">
            {t.contact.sampleNote}
          </p>
        </aside>

        <form
          onSubmit={onSubmit}
          className="rounded-3xl border border-border/60 bg-card/40 p-8 sm:p-10 lg:col-span-3"
        >
          <div className="grid gap-5 sm:grid-cols-2">
            <Field label={t.contact.fields.church} name="church" required />
            <Field label={t.contact.fields.country} name="country" required autoComplete="country-name" />
            <Field label={t.contact.fields.firstName} name="firstName" required autoComplete="given-name" />
            <Field label={t.contact.fields.lastName} name="lastName" required autoComplete="family-name" />
            <Field label={t.contact.fields.email} name="email" type="email" required autoComplete="email" />
            <Field label={t.contact.fields.phone} name="phone" type="tel" autoComplete="tel" />
            <Field label={t.contact.fields.congregation} name="congregation" placeholder={t.contact.placeholders.congregation} />
            <Field label={t.contact.fields.attendance} name="attendance" placeholder={t.contact.placeholders.attendance} />
            <Field label={t.contact.fields.quantity} name="quantity" placeholder={t.contact.placeholders.quantity} />
            <Field label={t.contact.fields.product} name="product" placeholder={t.contact.placeholders.product} />
          </div>

          <label className="mt-5 block">
            <span className="text-xs uppercase tracking-widest text-cream/60">{t.contact.fields.message}</span>
            <textarea
              name="message"
              rows={5}
              placeholder={t.contact.messagePlaceholder}
              className="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
            />
          </label>

          <label className="mt-6 flex items-start gap-3 text-sm text-cream/75">
            <input type="checkbox" name="notify" className="mt-1 h-4 w-4 accent-[color:var(--peach)]" />
            <span>{t.contact.notify}</span>
          </label>

          <button
            type="submit"
            disabled={submitting}
            className="mt-8 inline-flex w-full items-center justify-center gap-2 rounded-full bg-primary px-8 py-4 text-sm font-medium text-primary-foreground transition hover:brightness-110 disabled:opacity-60"
          >
            {submitting ? t.contact.submitting : t.contact.submit}
            <ArrowRight className="h-4 w-4" />
          </button>
        </form>
      </div>
    </main>
  );
}

function Field({
  label,
  name,
  type = "text",
  required,
  placeholder,
  autoComplete,
}: {
  label: string;
  name: string;
  type?: string;
  required?: boolean;
  placeholder?: string;
  autoComplete?: string;
}) {
  return (
    <label className="block">
      <span className="text-xs uppercase tracking-widest text-cream/60">{label}</span>
      <input
        type={type}
        name={name}
        required={required}
        placeholder={placeholder}
        autoComplete={autoComplete}
        className="mt-2 w-full rounded-xl border border-border bg-background/60 px-4 py-3 text-cream outline-none transition placeholder:text-cream/30 focus:border-primary focus:ring-2 focus:ring-primary/30"
      />
    </label>
  );
}
