// the-holy-supper-export/src/components/site/Footer.tsx
import { Link } from "@tanstack/react-router";
import { Cross } from "./Nav";
import { Instagram, Facebook, Mail, Phone } from "lucide-react";
import { useT, useLocale } from "@/i18n/config";

export function Footer() {
  const t = useT();
  const loc = useLocale();
  return (
    <footer className="border-t border-border/60 pt-20 pb-10">
      <div className="mx-auto max-w-7xl px-6">
        <div className="grid gap-12 lg:grid-cols-4">
          <div className="lg:col-span-2">
            <div className="flex items-center gap-2 text-primary">
              <Cross className="h-5 w-5" />
              <span className="text-display text-xl tracking-wide">The Holy Supper</span>
            </div>
            <p className="mt-4 max-w-md text-cream/70">{t.footer.tagline}</p>
            <div className="mt-6 flex flex-col gap-2 text-sm text-cream/70">
              <a href="mailto:theholysupper@gmail.com" className="inline-flex items-center gap-2 hover:text-primary">
                <Mail className="h-4 w-4" /> theholysupper@gmail.com
              </a>
              <a href="tel:+393913817351" className="inline-flex items-center gap-2 hover:text-primary">
                <Phone className="h-4 w-4" /> +39 391 3817351
              </a>
            </div>
            <div className="mt-6 flex gap-3">
              <a aria-label="Instagram" href="#" className="rounded-full border border-border p-2 text-cream/70 transition hover:text-primary">
                <Instagram className="h-4 w-4" />
              </a>
              <a aria-label="Facebook" href="#" className="rounded-full border border-border p-2 text-cream/70 transition hover:text-primary">
                <Facebook className="h-4 w-4" />
              </a>
            </div>
          </div>
          <div>
            <h4 className="text-sm font-semibold uppercase tracking-widest text-peach-soft">{t.footer.exploreTitle}</h4>
            <ul className="mt-4 space-y-2 text-sm text-cream/70">
              <li><a href={`/${loc}#why`} className="hover:text-primary">{t.nav.why}</a></li>
              <li><a href={`/${loc}#benefits`} className="hover:text-primary">{t.nav.benefits}</a></li>
              <li><a href={`/${loc}#pricing`} className="hover:text-primary">{t.nav.pricing}</a></li>
              <li><a href={`/${loc}#impact`} className="hover:text-primary">{t.nav.mission}</a></li>
              <li><a href={`/${loc}#faq`} className="hover:text-primary">{t.nav.faq}</a></li>
            </ul>
          </div>
          <div>
            <h4 className="text-sm font-semibold uppercase tracking-widest text-peach-soft">{t.footer.getInTouchTitle}</h4>
            <ul className="mt-4 space-y-2 text-sm text-cream/70">
              <li><Link to="/$locale/contact" params={{ locale: loc }} className="hover:text-primary">{t.footer.requestPricing}</Link></li>
              <li><Link to="/$locale/privacy" params={{ locale: loc }} className="hover:text-primary">{t.footer.privacyPolicy}</Link></li>
              <li><Link to="/$locale/cookies" params={{ locale: loc }} className="hover:text-primary">{t.footer.cookiePolicy}</Link></li>
              <li><Link to="/$locale/terms" params={{ locale: loc }} className="hover:text-primary">{t.footer.terms}</Link></li>
            </ul>
          </div>
        </div>
        <div className="divider-gilt my-12" />
        <div className="flex flex-col items-center justify-between gap-4 text-xs text-cream/50 sm:flex-row">
          <p>© {new Date().getFullYear()} The Holy Supper. {t.footer.rights}</p>
          <p className="tracking-widest uppercase">{t.footer.madeInItaly}</p>
        </div>
      </div>
    </footer>
  );
}

// src/app/shared/footer/footer.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { I18nService } from '../../i18n/i18n.service';
import { LucideAngularModule, Instagram, Facebook, Mail, Phone } from 'lucide-angular';

/* 
 * Componente Footer.
 */
@Component({
  selector: 'app-footer',
  standalone: true,
  imports: [CommonModule, RouterModule, LucideAngularModule],
  templateUrl: './footer.component.html'
})
export class FooterComponent {
  i18n = inject(I18nService);
  
  icons = { Instagram, Facebook, Mail, Phone };
  currentYear = new Date().getFullYear();

  get t() {
    return this.i18n.getTranslation().footer;
  }

  get navT() {
    return this.i18n.getTranslation().nav;
  }

  get locale() {
    return this.i18n.currentLocale();
  }
}

<footer class="border-t border-border/60 pt-20 pb-10">
  <div class="mx-auto max-w-7xl px-6">
    <div class="grid gap-12 lg:grid-cols-4">
      <div class="lg:col-span-2">
        <div class="flex items-center gap-2 text-primary">
          <svg viewBox="0 0 24 24" fill="none" class="h-5 w-5" aria-hidden="true">
            <path d="M12 2v20M6 8h12" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" />
          </svg>
          <span class="text-display text-xl tracking-wide">The Holy Supper</span>
        </div>
        <p class="mt-4 max-w-md text-cream/70">{{ t.tagline }}</p>
        <div class="mt-6 flex flex-col gap-2 text-sm text-cream/70">
          <a href="mailto:theholysupper@gmail.com" class="inline-flex items-center gap-2 hover:text-primary">
            <lucide-icon [img]="icons.Mail" class="h-4 w-4"></lucide-icon> theholysupper@gmail.com
          </a>
          <a href="tel:+393913817351" class="inline-flex items-center gap-2 hover:text-primary">
            <lucide-icon [img]="icons.Phone" class="h-4 w-4"></lucide-icon> +39 391 3817351
          </a>
        </div>
        <div class="mt-6 flex gap-3">
          <a aria-label="Instagram" href="#" class="rounded-full border border-border p-2 text-cream/70 transition hover:text-primary">
            <lucide-icon [img]="icons.Instagram" class="h-4 w-4"></lucide-icon>
          </a>
          <a aria-label="Facebook" href="#" class="rounded-full border border-border p-2 text-cream/70 transition hover:text-primary">
            <lucide-icon [img]="icons.Facebook" class="h-4 w-4"></lucide-icon>
          </a>
        </div>
      </div>
      
      <div>
        <h4 class="text-sm font-semibold uppercase tracking-widest text-peach-soft">{{ t.exploreTitle }}</h4>
        <ul class="mt-4 space-y-2 text-sm text-cream/70">
          <li><a [href]="'/' + locale + '#why'" class="hover:text-primary">{{ navT.why }}</a></li>
          <li><a [href]="'/' + locale + '#benefits'" class="hover:text-primary">{{ navT.benefits }}</a></li>
          <li><a [href]="'/' + locale + '#pricing'" class="hover:text-primary">{{ navT.pricing }}</a></li>
          <li><a [href]="'/' + locale + '#impact'" class="hover:text-primary">{{ navT.mission }}</a></li>
          <li><a [href]="'/' + locale + '#faq'" class="hover:text-primary">{{ navT.faq }}</a></li>
        </ul>
      </div>
      
      <div>
        <h4 class="text-sm font-semibold uppercase tracking-widest text-peach-soft">{{ t.getInTouchTitle }}</h4>
        <ul class="mt-4 space-y-2 text-sm text-cream/70">
          <li><a [routerLink]="['/', locale, 'contact']" class="hover:text-primary">{{ t.requestPricing }}</a></li>
          <li><a [routerLink]="['/', locale, 'privacy']" class="hover:text-primary">{{ t.privacyPolicy }}</a></li>
          <li><a [routerLink]="['/', locale, 'cookies']" class="hover:text-primary">{{ t.cookiePolicy }}</a></li>
          <li><a [routerLink]="['/', locale, 'terms']" class="hover:text-primary">{{ t.terms }}</a></li>
        </ul>
      </div>
    </div>
    
    <div class="divider-gilt my-12"></div>
    
    <div class="flex flex-col items-center justify-between gap-4 text-xs text-cream/50 sm:flex-row">
      <p>© {{ currentYear }} The Holy Supper. {{ t.rights }}</p>

      <div class="flex items-center gap-2 text-cream/70 transition-colors hover:text-cream">
        <span>{{ t.createdBy }}</span>
        <svg viewBox="0 0 100 100" class="h-6 w-6 shrink-0 inline-block text-cream/80 hover:text-cream transition-colors" aria-label="Logo PQ">
          <!-- Outer circle Q -->
          <circle cx="45" cy="45" r="33" stroke="currentColor" stroke-width="10" fill="none" />
          <!-- Q Tail -->
          <line x1="64" y1="64" x2="84" y2="84" stroke="currentColor" stroke-width="14" stroke-linecap="square" />
          <!-- P Letter inside -->
          <path d="M 34,25 V 65 M 34,25 H 52 C 62,25 62,45 52,45 H 34" stroke="currentColor" stroke-width="10" stroke-linecap="square" stroke-linejoin="miter" fill="none" />
        </svg>
      </div>

      <p class="tracking-widest uppercase">{{ t.madeInItaly }}</p>
    </div>
  </div>
</footer>
